/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "test-gpt-dc-30072023-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d26bonaziogk1b.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:94bec7ce-ef5c-4079-ae8a-47c66de9f989",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DrkIkoKQA",
    "aws_user_pools_web_client_id": "51d1i8utp9d48m77sgqq60ie4f",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apigpt",
            "endpoint": "https://8dd8u4svh6.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "predictions": {
        "convert": {
            "speechGenerator": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Mia",
                    "LanguageCode": "es-MX"
                }
            }
        }
    }
};


export default awsmobile;
